### ISSUE TITLE
Processing not working

### ISSUE THREAD

**Issue by jdellano** [tabreturn/processing.py-book#1]
Hello, I am frustrated; I bought the book Learn Python Visually and installed Processing on my iMac with Big Sur. I followed all instructions and then uninstalled and reinstalled the program but there is no output. Not even output when I run the examples. Hope someone can help! 
Thanks. 
Juan

**Comment by tabreturn** [comment]
Please install Processing 3.5.4. Python Mode for Processing 4 is still under development.
